language: node_js
node_js:
  - '9'
env:
  global:
    - CC_TEST_REPORTER_ID=7e7c4022ca08be21036b02154ca411c8dee3131ac067f050e6ad07932b55971d
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
  - npm install
  - npm install -g jest-cli
script:
  - CI=false npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
